# Synthetic archive in the same file layout as Armstrong; intentionally coarse grid.
script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
if (!length(script_arg)) stop("Could not determine the location of examples/make_demo.R.")
script_path <- normalizePath(sub("^--file=", "", script_arg[[1]]), mustWork = TRUE)
repo_root <- normalizePath(file.path(dirname(script_path), ".."), mustWork = TRUE)
local_library <- file.path(repo_root, ".R-library")
if(dir.exists(local_library)) .libPaths(c(local_library,.libPaths()))
if(!requireNamespace("ncdf4",quietly=TRUE))stop("Run steps/00_setup.R first.")
set.seed(91)
root<-file.path(repo_root,"examples","generated"); dir.create(root,recursive=TRUE,showWarnings=FALSE)
lon<-seq(-10,130,10); lat<-seq(35,65,5); cells<-expand.grid(lon=lon,lat=lat)
write_nc<-function(variable,folder,prefix,monthly,units) {
  directory<-file.path(root,"climate",folder); dir.create(directory,recursive=TRUE,showWarnings=FALSE)
  nt<-if(monthly)30000L else 2500L
  dimensions<-list(ncdf4::ncdim_def("lon","degrees_east",lon),ncdf4::ncdim_def("lat","degrees_north",lat),ncdf4::ncdim_def("time",if(monthly)"months after -550-1-1 0:0:0" else "years after -550-1-1 0:0:0",seq_len(nt)))
  nc<-ncdf4::nc_create(file.path(directory,paste0(prefix,"0_2.5kyr.nc")),ncdf4::ncvar_def(variable,units,dimensions,-9999,prec="float",compression=4))
  on.exit(ncdf4::nc_close(nc))
  for(first in seq(1,nt,by=if(monthly)1200 else 100)) {
    count<-min(if(monthly)1200 else 100,nt-first+1); ii<-seq(first,length.out=count)
    age<-2.5-(ii-1)/(if(monthly)12000 else 1000)
    values<-vapply(seq_along(ii),function(j) {
      season<-cos(2*pi*((ii[j]-1)%%12-6)/12)
      if(variable=="tas") return(14-.48*(cells$lat-35)-.012*cells$lon-2*age[j]+(7+.025*cells$lon)*season)
      if(variable=="pr") return(pmax(.05,2+.009*cells$lon+.018*(cells$lat-50)+.4*sin(age[j]*2)+(.45+.001*cells$lon)*season))
      if(variable=="sftlf") return(as.numeric(!(cells$lon<10 & cells$lat>55)))
      as.numeric(cells$lat>=60+3*(2.5-age[j]))
    },numeric(nrow(cells)))
    ncdf4::ncvar_put(nc,variable,array(values,c(length(lon),length(lat),count)),start=c(1,1,first),count=c(length(lon),length(lat),count))
  }
}
write_nc("tas","temp_nc","bias_regrid_tas_",TRUE,"DegC")
write_nc("pr","precip_nc","bias_regrid_pr_",TRUE,"mm day-1")
write_nc("sftlf","landmask_nc","regrid_landmask_",FALSE,"%")
write_nc("sftgif","icefrac_nc","regrid_icefrac_",FALSE,"%")
sites<-cells[cells$lat<=55 & cells$lon>=0,]; sites<-sites[sample.int(nrow(sites),32),]
schema<-read.csv(file.path(repo_root,"templates","fossils.csv")); x<-as.data.frame(setNames(replicate(ncol(schema),rep(NA,32),simplify=FALSE),names(schema)))
x$record_id<-sprintf("DEMO_%02d",1:32); x$specimen_id<-x$record_id; x$site_id<-sprintf("SITE_%02d",1:32)
x$taxon<-"Synthetic species"; x$site<-x$site_id; x$longitude<-sites$lon; x$latitude<-sites$lat
x$coordinate_uncertainty_km<-0; x$date_type<-"radiocarbon"; x$age_14c_bp<-sample(seq(600,2000,50),32,replace=TRUE); x$error_14c_bp<-40
x$material<-"synthetic bone"; x$quality_class<-"teaching_only"; x$include<-TRUE
x$reference<-"Generated by examples/make_demo.R; not real fossils"; x$notes<-"SYNTHETIC"
x$date_type[1]<-"calibrated_range"; x$age_14c_bp[1]<-x$error_14c_bp[1]<-NA; x$cal_young_bp[1]<-1200; x$cal_old_bp[1]<-1400; x$calibration_reference[1]<-"Synthetic example only"
x$include[32]<-FALSE; x$exclusion_reason[32]<-"Example quality exclusion"
write.csv(x,file.path(root,"fossils.csv"),row.names=FALSE,na="")
message("Synthetic data ready. From the repository root, run Rscript steps/01_fossils.R config/demo.R; inspect the map before proceeding.")
