source("R/common.R"); p <- load_project(); step <- "01_fossils"
x <- read.csv(p$fossil_file,check.names=FALSE,na.strings=c("","NA"))
cols <- names(read.csv("templates/fossils.csv"))
if (!all(cols %in% names(x))) stop("Missing columns: ",paste(setdiff(cols,names(x)),collapse=", "))
if (!nrow(x) || anyNA(x$record_id) || anyDuplicated(x$record_id)) stop("record_id must be nonempty and unique.")
if (!is.logical(x$include) || anyNA(x$include)) stop("include must contain TRUE or FALSE for every row.")
reason <- rep("",nrow(x))
add <- function(bad,msg) {bad[is.na(bad)] <- TRUE; reason[bad] <<- paste0(reason[bad],msg,"; ")}
add(!is.finite(x$longitude)|abs(x$longitude)>180|!is.finite(x$latitude)|abs(x$latitude)>90,"invalid coordinates")
add(!x$date_type %in% c("radiocarbon","calibrated_range"),"unsupported date_type")
add(x$date_type=="radiocarbon" & (!is.finite(x$age_14c_bp)|x$age_14c_bp<=0|!is.finite(x$error_14c_bp)|x$error_14c_bp<=0),"radiocarbon age/error missing or invalid")
add(x$date_type=="calibrated_range" & (!is.finite(x$cal_young_bp)|!is.finite(x$cal_old_bp)|x$cal_young_bp<0|x$cal_old_bp<x$cal_young_bp|is.na(x$calibration_reference)),"invalid calibrated range or missing calibration reference")
for (col in c("site_id","specimen_id","taxon","reference","quality_class")) add(is.na(x[[col]])|!nzchar(trimws(x[[col]])),paste("missing",col))
add(is.finite(x$coordinate_uncertainty_km)&x$coordinate_uncertainty_km<0,"negative coordinate uncertainty")
if (any(!x$include & (is.na(x$exclusion_reason)|!nzchar(x$exclusion_reason)))) stop("Excluded rows need an exclusion_reason.")
x$validation_issue <- reason; table_out(p,step,"audit",x)
if (any(x$include & nzchar(reason))) stop("Included records have errors. Read outputs/*/01_fossils/audit.csv and correct the source table.")
accepted <- x[x$include,]; if (nrow(accepted)<8) stop("Need at least eight independent fossils for this teaching workflow.")
if (anyDuplicated(accepted$specimen_id)) stop("Multiple included dates for one specimen. Resolve redates upstream; see data dictionary.")
sites <- split(accepted,accepted$site_id)
if (any(vapply(sites,function(s) length(unique(paste(s$longitude,s$latitude)))>1,logical(1)))) stop("Use one agreed coordinate for each site_id.")
write_output(p,step,"fossils",accepted); table_out(p,step,"accepted",accepted)
plot_out(p,step,"occurrences",point_map(accepted))
complete_step(p,step,p$fossil_file,list(),c(paste(nrow(accepted),"included records from",length(sites),"sites."),"Check taxonomy, synonyms, coordinates, pretreatment and chronology against original sources."))
